### ISSUE TITLE
is this action usable?

### ISSUE THREAD

**Issue by danieleades** [actions-rs-plus/clippy-check#105]
looks like `actions-rs/clippy-check` is unmaintained, so this fork may not get merged. I'd love to use it. Is it published anywhere?

**Comment by simonsso** [comment]
@adam-azarchs @danieleades Have you moved on to a new fork somewhere?

**Comment by adam-azarchs** [comment]
We've moved to 10XGenomics/clippy-check.  I don't think we can guarantee a lot of ongoing support beyond features we need internally, though we'll at least be merging dependabot security updates. And we've tagged a release.

**Comment by danieleades** [comment]
I'm using https://github.com/giraffate/clippy-action

**Comment by kristof-mattei** [comment]
You're welcome to use this one. I'm trying to keep it up to date.
