### ISSUE TITLE
Failing without logs

### ISSUE THREAD

**Issue by danieleades** [actions-rs-plus/clippy-check#441]
I'm seeing an issue where this action is failing and not producing any useful output to determine what's going on. Hoping you can help.

The PR in question is here - https://github.com/danieleades/cosmic-applets/pull/1

The thing is, I *expect* the build to fail because I know there are some packages missing from the host, but I can't see *why* the job is failing to correct it.

I've added the missing packages, job is still failing. Red herring.

**Comment by kristof-mattei** [comment]
On it.

**Comment by kristof-mattei** [comment]
Bug found. Squashing.

**Comment by kristof-mattei** [comment]
Fixed in https://github.com/actions-rs-plus/clippy-check/releases/tag/v2.2.0

**Comment by danieleades** [comment]
thanks for the quick turnaround!
